[21기 신미영] Add: 상품 상세페이지 1차  Commit
wecode-bootcamp-korea/21-1st-Biskit-frontend pull request #5
Opened 2021-06-10 06:16 UTC by smy0102

## 수정 사항 간략한 한줄 요약
- [21기 신미영] Add: 상품 상세페이지 1차  Commit
		 
## 수정 사항들 자세한 내용
### **1. 레이아웃 및 스타일링**
- 전체적인 틀은 완성했으나 상세설명, 상품정보, 리뷰, 배송/반품/문의 탭 영역을 작업하지 못했습니다ㅠㅠ 
- 배송받을 날짜 영역 select 태그 사용, 장바구니/선물하기 버튼 영역 삭제 등 일부 스타일링 간소화 했습니다.

### **2. 기능 구현**
- 상단 상품 이미지 캐러셀(?) 기능 Mock data 사용하여 구현 완료 하였습니다. 
- 그 외의 텍스트들은 현재 하드코딩으로 들어가 있습니다ㅠㅠ 

## 기타 질문 및 특이 사항
- 컴포넌트 파일들이 현재 Component 폴더 안에 그대로 들어가 있는데, 컴포넌트별로 폴더를 생성해서 js파일과 scss파일을 관리하는 것이 나을까요???

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-10 06:19 UTC, dipsiiiiiiiiii commented
질문에 대한 답변 먼저 드리면, 

컴포넌트별로 폴더를 생성해서 js, scss 파일 나눠서 관리하는 게 더 좋을 것 같아요! 가독성!

2021-06-10 06:33 UTC, dipsiiiiiiiiii reviewed
고생하셨습니다 미영님! 예쁘게 잘 만드셨네요!

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on public/data/ProdDetail/picturesData.json
> +  {
js, json 둘 다 필요하신가요?

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/productPictures.scss
> +    height: 600px;
이미지는 width나 height 하나만 주셔야 비율이 맞습니다

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/productPictures.scss
> +      height: 90px;
여기도 마찬가지!

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/DetailBody.js
> +              <option value="날짜5">날짜5</option>
날짜가 늘어날 수도 있으니 map 활용해 보시면 좋을 것 같습니다.

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/DetailBody.js
> +          <article className="delivery"></article> */}
필요 없으시면 주석 제거해 주세요

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/ProductPictures.js
> +    fetch('http://localhost:3000/data/ProdDetail/picturesData.json', {
```suggestion
    fetch('/data/ProdDetail/picturesData.json', {
```

이렇게 줄일 수도 있습니다

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/ProductPictures.js
> +      method: 'GET',
method default가 get이라 적지 않으셔도 됩니다.

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/bodyPutCart.scss
> +    height: 36px;
버튼의 높이는 height보다는 font-size와 padding으로만 하는게 좋습니다. font-size가 바뀌면 height도 또 바꿔줘야 하기 때문입니다.

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/cartInformation.scss
> +  // display: none;
주석 지워 주세요

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/detailHead.scss
> +}
mixin은 다른 곳에서도 사용할 수 있기 때문에 분리해 주세요.

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/detailHead.scss
> +            height: 22px;
이미지는 가로, 세로 하나만!

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/detailBody.scss
> +        height: 50px;
여기도 height대신 font-size와 padding으로!

2021-06-10 06:33 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/DetailHead.js
> +              <option value="날짜5">날짜5</option>
이것도 map 활용해 보세요!

2021-06-10 06:35 UTC, smy0102 commented on public/data/ProdDetail/picturesData.json
> +  {
아닙니다..ㅎㅎ js 파일 삭제하겠습니다!

2021-06-10 06:55 UTC, smy0102 commented on src/Components/ProdDetail/productPictures.scss
> +    height: 600px;
수정했습니다!

2021-06-10 06:55 UTC, smy0102 commented on src/Components/ProdDetail/productPictures.scss
> +      height: 90px;
수정했습니다!

2021-06-10 06:56 UTC, smy0102 commented on src/Components/ProdDetail/DetailBody.js
> +          <article className="delivery"></article> */}
넵 제거했습니다~!

2021-06-10 06:56 UTC, smy0102 commented on src/Components/ProdDetail/ProductPictures.js
> +    fetch('http://localhost:3000/data/ProdDetail/picturesData.json', {
넵! 줄여서 사용하겠습니다!

2021-06-10 06:56 UTC, smy0102 commented on src/Components/ProdDetail/ProductPictures.js
> +      method: 'GET',
넵, 삭제했습니다!

2021-06-10 07:01 UTC, smy0102 commented on src/Components/ProdDetail/detailHead.scss
> +            height: 22px;
수정했습니다!

2021-06-10 07:05 UTC, smy0102 commented on src/Components/ProdDetail/detailHead.scss
> +}
분리했습니다~

2021-06-10 07:06 UTC, smy0102 commented on src/Components/ProdDetail/cartInformation.scss
> +  // display: none;
해당 영역이 원래 보이지 않다가 배송 날짜를 선택하면 노출되는 영역이라... 레이아웃 확인용으로 남겨놓고자 합니다. 기능 구현 완료 후 정리 하겠습니다~!

2021-06-10 07:36 UTC, smy0102 commented on src/Components/ProdDetail/detailBody.scss
> +        height: 50px;
수정했습니다!

2021-06-10 07:44 UTC, smy0102 commented on src/Components/ProdDetail/bodyPutCart.scss
> +    height: 36px;
수정했습니다!

2021-06-11 06:33 UTC, smy0102 commented on src/Components/ProdDetail/DetailHead.js
> +              <option value="날짜5">날짜5</option>
수정했습니다!

2021-06-11 06:33 UTC, smy0102 commented on src/Components/ProdDetail/DetailBody.js
> +              <option value="날짜5">날짜5</option>
수정했습니다!

2021-06-15 01:29 UTC, dipsiiiiiiiiii requested changes
고생 많으셨습니다 미영님!

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Styles/ProdDetail/_mixin.scss
> +}
mixin을 폴더별로 나누셨는데 그럴 필요 없습니다. 
여러 컴포넌트에서 사용할 수 있기 때문에 폴더 안에 넣은 mixin들 전부 최상위로 넣어 주세요

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/OrderInformation/OrderInformation.js
> +          style={!isSelectBoxOn ? { display: 'none' } : {}}
이렇게도 가능하지만 가독성을 위해서 다음과 같이 하는 것이 더 좋을 것 같습니다.
```suggestion
          style={{ display: !isSelectBoxOn ? "none" : "block" }}
```

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/ProductPictures/ProductPictures.js
> +        const pictureArr = data.result.detail_image;
비구조화 사용해 주세요!

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/ProductPictures/ProductPictures.js
> +                src={picture}
map 인자로 받는 콜백 함수의 두번째 인자가 index라서 아래와 같이 할 수 있습니다.
그리고 map의 key로 index를 잘 쓰지 않는데 그 이유에 대해서도 알아보면 좋을 것 같습니다.
```suggestion
          {pictureList.map((picture, index) => {
            return (
              <img
                className={mainPictureSrc === picture && 'picturefocusOn'}
                alt="product"
                key={index}
                src={picture}
```

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/TapContents/Description.js
> +        const descriptionInfoArr = data.description_info;
여기도 비구조화!

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/TapContents/Information.js
> +        const descriptionInfoArr = data.description_info;
여기도!

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Components/ProdDetail/TapList/TapList.js
> +const tapArr = ['상세설명', '상품정보', '리뷰', '배송/반품/문의'];
JavaScript에서 상수 컨벤션은 TAP_ARR 대문자_대문자 입니다. 참고해 주세요 :)

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Pages/ProdDetail/ProdDetail.js
> +};
굿!

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Pages/ProdDetail/ProdDetail.js
> +    const weekName = ['일', '월', '화', '수', '목', '금', '토'];
이런 것들도 공통으로 같이 쓸 수 있어서 상수로 관리하고 팀원분들이 다 같이 사용하면 좋을 것 같습니다.

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Pages/ProdDetail/ProdDetail.js
> +      );
조건문으로 value가 없을 때를 먼저 제거하고 시작하면 코드가 깔끔할 것 같습니다.

2021-06-15 01:29 UTC, dipsiiiiiiiiii commented on src/Pages/ProdDetail/ProdDetail.js
> +  };
비슷한 일을 하고 있는 함수인데 하나로 합쳐볼 수 있을 것 같습니다. ```handleQuantity```라는 이름 추천드립니다👍

2021-06-15 02:28 UTC, smy0102 commented on src/Components/ProdDetail/OrderInformation/OrderInformation.js
> +          style={!isSelectBoxOn ? { display: 'none' } : {}}
넵, 감사합니다!

2021-06-15 03:57 UTC, smy0102 commented on src/Components/ProdDetail/ProductPictures/ProductPictures.js
> +                src={picture}
두 번째 인자 index로 넣어 수정했습니다. 
배열의 index를 key로 넣을 경우 배열이 재배열 된다면 컴포넌트가 re-rendering 되고 항목의 순서가 바뀌었을 때 key가 바뀌면서 state 순서가 엉망이 될 수 있어 쓰지 않는 점 확인 했습니다! 감사합니다~

2021-06-15 03:58 UTC, smy0102 commented on src/Components/ProdDetail/TapList/TapList.js
> +const tapArr = ['상세설명', '상품정보', '리뷰', '배송/반품/문의'];
넵, 수정 했습니다!

2021-06-15 03:58 UTC, smy0102 commented on src/Pages/ProdDetail/ProdDetail.js
> +};
😀

2021-06-15 04:11 UTC, smy0102 commented on src/Styles/ProdDetail/_mixin.scss
> +}
넵, mixin 파일 최상위 폴더로 이동 시켰습니다!

2021-06-15 04:36 UTC, smy0102 commented on src/Components/ProdDetail/ProductPictures/ProductPictures.js
> +        const pictureArr = data.result.detail_image;
넵, 수정했습니다!

2021-06-15 04:37 UTC, smy0102 commented on src/Components/ProdDetail/TapContents/Description.js
> +        const descriptionInfoArr = data.description_info;
넵, 수정했습니다!

2021-06-15 04:37 UTC, smy0102 commented on src/Components/ProdDetail/TapContents/Information.js
> +        const descriptionInfoArr = data.description_info;
넵, 수정했습니다!

2021-06-15 04:54 UTC, smy0102 commented on src/Pages/ProdDetail/ProdDetail.js
> +    const weekName = ['일', '월', '화', '수', '목', '금', '토'];
넵, js파일로 만들어 src > Data 폴더에 추가했습니다.

2021-06-15 07:43 UTC, smy0102 commented on src/Pages/ProdDetail/ProdDetail.js
> +  };
넵, handleQuantity로 합쳤습니다! 

  handleQuantity = button => {
    if (button.target.className === 'quantityPlus') {
      this.setState(
        state => ({
          quantity: state.quantity + 1,
        }),
        () => this.calculatePrice()
      );
    } else {
      if (this.state.quantity === 1) {
        alert('최소 1개 이상 구매하셔야 합니다. 수량을 변경해 주세요.');
      } else {
        this.setState(
          state => ({
            quantity: state.quantity - 1,
          }),
          () => this.calculatePrice()
        );
      }
    }
  };

2021-06-15 10:57 UTC, smy0102 commented on src/Pages/ProdDetail/ProdDetail.js
> +  };
handleQuantity = word => {
    const { quantity } = this.state;

    if (word === 'minus' && quantity === 1) {
      alert('최소 1개 이사 구매하셔야 합니다. 수량을 변경해 주세요.');
      return;
    }

    this.setState(
      {
        quantity: word === 'plus' ? quantity + 1 : quantity - 1,
      },
      this.calculatePrice
    );
  };

2021-06-15 11:11 UTC, smy0102 commented on src/Pages/ProdDetail/ProdDetail.js
> +      );
알려 주신 방법대로 앞으로 해 보겠습니다!

2021-06-16 06:52 UTC, merged